### ISSUE TITLE
SimulatedPlayer class 

### ISSUE THREAD

**Issue by JaylyDev** [JaylyDev/ScriptAPI#129]
**Describe the bug**

Caused by #128 

SimulatedPlayer class doesn't seem to extend Player class in latest typings, which cause most scripts that uses SimulatedPlayer class to have errors thrown by tsc.

Currently causes `simulated-player` to have errors thrown by tsc.

**Expected behavior**

SimulatedPlayer class extends Player class.

**Screenshots**

Before and after:

![image](https://media.discordapp.net/attachments/1038186310294310942/1078713749222985810/image.png?width=1440&height=240)

**Comment by JaylyDev** [comment]
In older versions of types you're able to get a property from Player class in a simulatedplayer instance because it extends Player class. So I can do `simPlayer.viewDirection` and not have any problems. Now they removed the extends and typings now detects `simPlayer.viewDirection` as not a property of SimulatedPlayer class

**Comment by ConsoleTerm** [comment]
> In older versions of types you're able to get a property from Player class in a simulatedplayer instance because it extends Player class. So I can do `simPlayer.viewDirection` and not have any problems. Now they removed the extends and typings now detects `simPlayer.viewDirection` as not a property of SimulatedPlayer class

That is not true because all extending was fake and only what was having a impack on TS was extends keyword in type definition files, but simlutated player have all properties of players and entities it selfs, so nothing changes, here is example of old types
![image](https://user-images.githubusercontent.com/64863757/222184990-14087056-2846-4440-a71f-f76169f42939.png)
See? there are properties such as id or dimension what should be inherited from entity but player has it it self so when u remove extends keyword then nothing changes in TS, is that right?

**Comment by JaylyDev** [comment]
[![image](https://user-images.githubusercontent.com/65847850/222187750-eea81899-2dca-4966-b874-1124eeda1738.png)
](https://github.com/JaylyDev/ScriptAPI/actions/runs/4284632986/jobs/7461861845)

**Comment by ConsoleTerm** [comment]
Thx, for linking it for me i will look at this issue when new preview arrive today, to be sure engine and types for engine is same version, keep this issue as open

**Comment by JaylyDev** [comment]
This issue is fixed by #141
