### ISSUE TITLE
I can't use JaylyDB in strict mode + Doesn't work in 1.20.0/1.20.1

### ISSUE THREAD

**Issue by ImLighty** [JaylyDev/ScriptAPI#279]
**Describe the bug**
There's issues in the code when using strict mode. Also, I can't use this code without being in the 1.20.10 preview

**Expected behavior**
I don't know

**Screenshots**
![image](https://github.com/JaylyDev/ScriptAPI/assets/45460688/7963f057-950c-4f24-93d7-f50f803f4af3)
![image](https://github.com/JaylyDev/ScriptAPI/assets/45460688/89d9371c-e1a3-4a26-bc30-09a4badfdb48)
![image](https://github.com/JaylyDev/ScriptAPI/assets/45460688/b43930db-bf24-413c-a762-085e13f48ecd)

**Comment by ConsoleTerm** [comment]
not sure for what are you need strict mode, but i am sure the version is intended, we got new possibilities since 1.20.10 arrived and Jayly makes the database for the 1.20.10 before stable release so you are able to use it in development before stable breaks your code, 
can you provide me on how are you using his DB in strict mode?
